apply the workaround asynchronously
With the previous way, 1. timeout had to be reached and 2. re-running
the sunbeam command after the charm refresh was too early.

+ sunbeam cluster bootstrap --manifest manifest.yaml
Timed out while waiting for model 'controller' to be ready
Error: Timed out while waiting for model 'controller' to be ready
+ juju refresh -m controller sunbeam-clusterd --revision 16 --force-units
Added charm-hub charm "sunbeam-clusterd", revision 16 in channel 2024.1/edge, to the model
no change to endpoint in space "alpha": peers
+ sunbeam cluster bootstrap --manifest manifest.yaml
Error: {'return-code': 1, 'stderr': 'Uncaught InvalidURL in charm code:
Not supported URL scheme http+unix\nUse `juju debug-log` to see the full
traceback.\n'}